preset: angular
infile: CHANGELOG.md
strictSemVer: true
header: |
  # DekTek Changelog

  All notable changes are listed below.
  
types:
  - type: BREAKING CHANGE
    section: "âš ï¸ Major Changes"
  - type: refactor
    section: "âš ï¸ Major Changes"
  - type: fix
    section: "ğŸ› Bug Fixes"
  - type: hotfix
    section: "ğŸ› Bug Fixes"
  - type: feat
    section: "âœ¨ New Features"
  - type: docs
    section: "ğŸ› ï¸ Miscellaneous"
  - type: style
    section: "ğŸ› ï¸ Miscellaneous"
  - type: test
    section: "ğŸ› ï¸ Miscellaneous"
  - type: chore
    section: "ğŸ› ï¸ Miscellaneous"

commitPartial: "- {{type}}: {{subject}} ({{hash}})"