preset: angular
infile: CHANGELOG.md
strictSemVer: true
header: |
  # DekTek Changelog

  All notable changes are listed below.
  
types:
  - BREAKING CHANGE: "major"
    section: "âš ï¸ Major Changes"
  - refactor: "major"
    section: "âš ï¸ Major Changes"
  - fix: "patch"
    section: "ğŸ› Bug Fixes"
  - hotfix: "patch"
    section: "ğŸ› Bug Fixes"
  - feat: "minor"
    section: "âœ¨ New Features"
  - docs: "minor"
    section: "ğŸ› ï¸ Miscellaneous"
  - style: "minor"
    section: "ğŸ› ï¸ Miscellaneous"
  - test: "minor"
    section: "ğŸ› ï¸ Miscellaneous"
  - chore: "minor"
    section: "ğŸ› ï¸ Miscellaneous"

commitPartial: "- {{type}}: {{subject}} ({{hash}})"